export const MentorsDataBase = [
    { id: 1,
      name: 'Ramadugu Nagendra Chari',
      email: 'nagendrachariramadugu@gmail.com',
      gender: 'male',
      dob: '2002-08-02',  
      degree: 'B-Tech',
      domain: 'Full Stack Development',
      skills: 'Problem Solving, Git Git Hub, Full Stack development(MERN), Python, C++, C',
      password: 'chari@2002',
      about: '',
      description: ''
    },
    { id: 2,
      name: 'Krishna Pedakolimi',
      email: 'chaitanyasiva30@gmail.com',
      gender: 'male',
      dob: '2002-01-01',  
      degree: 'B-Tech',
      domain: 'Full Stack Development',
      skills: 'Problem Solving, Git Git Hub, Full Stack development(MERN), Python, C++, C',
      password: 'krishna@2002',
      about: '',
      description: ''
    },
    { id: 3,
      name: 'Naffesa Pathan',
      email: 'naffesapathan30@gmail.com',
      gender: 'female',
      dob: '2002-09-07',  
      degree: 'B-Tech',
      domain: 'Full Stack Development',
      skills: 'Problem Solving, C, Python, Front End',
      password: 'naffesa@2002',
      about: '',
      description: ''
    },
    { id: 4,
      name: 'Teja Regulagunta',
      email: 'tejaregulagunta30@gmail.com',
      gender: 'male',
      dob: '2002-07-30',  
      degree: 'B-Tech',
      domain: 'Full Stack Development',
      skills: 'Problem Solving, Git Git Hub, Full Stack development(MERN), Python, C++, C',
      password: 'teja@2002',
      about: '',
      description: ''
    }
  ]